
- name: setup configuration
  template: src=ffserver.conf dest=/etc/ffserver.conf

- name: run ffserver
  shell: ffserver -f /etc/ffserver.conf &

- name: setup-decoding
  shell: avconv -v verbose -f video4linux2 -i /dev/video0 http://localhost/webcam.ffm &
